### ISSUE TITLE
Missing multipart/form-data content-type

### ISSUE THREAD

**Issue by rayshan** [montagestudio/montage-data#8]
Since this is available:
https://github.com/montagestudio/montage-data/blob/master/logic/service/http-service.js#L28

This should probably be available too:
https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2

Not a big deal, developers can just create their own constants.

**Comment by hthetiot** [comment]
Nah you can do post via "this.fetchHttpRawData(url, null, body, false)" from a service.
